apiVersion: v1
kind: Pod
metadata:
  name: devops-01-hello
  labels:
    app.kubernetes.io/name: devops-01-hello
    my-type: backend
    my-app: hello-module 
    my-project-name: mydemo
spec:
  containers:
  - name: devops-01-hello
    image: mimaraslan/devops-01-hello:v001
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9091
---
apiVersion: v1
kind: Pod
metadata:
  name: devops-01-hello2
  labels:
    app.kubernetes.io/name: devops-01-hello2
    my-type: frontend
    my-app: hello-module2 
    my-project-name: mydemo
spec:
  containers:
  - name: devops-01-hello2
    image: mimaraslan/devops-01-hello:v002
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9092
---
apiVersion: v1
kind: Pod
metadata:
  name: devops-01-hello3
  labels:
    app.kubernetes.io/name: devops-01-hello3
    my-type: frontend
    my-app: hello-module3
    my-project-name: mydemo
spec:
  containers:
    - name: devops-01-hello2
      image: mimaraslan/devops-01-hello:v003
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 9093
