apiVersion: v1
kind: Service
metadata:
  name: devops-01-hello
spec:
  selector:
    app: devops-01-hello
  ports:
  - port: 9090 # servise yapilacak isteklerin dis portu
    targetPort: 8080 # bu port kendisine baglanan podlarin portlari olmak zorindadir
